### ISSUE TITLE
Top 5 Items for Microsite, Phase II

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox-microsite#62]
Here is a list of top five priorities in priority oder with links to tracking bugs for each.

- [ ] [Migration guide](https://github.com/GoogleChrome/workbox/issues/109).
- [ ] Item
- [ ] Item

**Comment by tjsavage** [comment]
A couple ideas:

- "Tutorial." This would likely be a big project, but I could see a tutorial that walks through how to build a simple PWA, showing step-by-step each kind of feature that the Workbox modules can help provide support for. An easily-discoverable, high-level guide sort of like we had for [sw-toolbox](https://googlechrome.github.io/sw-toolbox/usage.html#main) seems useful. E.g. using maybe a simple TodoMVC-like demo, showing "here's how to get basic offline," "here's basic precaching," "here's how an update would work," "here's a basic background sync for syncing changes that were made while offline," "here's how you'd use google analytics," etc.
- "Troubleshooting/Debugging." Since working with SW can sometimes lead to a wider set of "heisenbugs" than a typical API, a section that identifies common problems that a dev might run into with ways to fix them could be useful.
- Spruced up homepage. I think the landing page could use a little more explanatory copy - particularly above "getting started" - that succinctly explains what Workbox does. Happy to draft up some ideas if it would be helpful.
- Cleaned up "Reference." Information hierarchy in "Reference" section is a little hard to grok. I think a general "cleanup" effort here might go a long way. From small visual tweaks for readability like making the dropdown menu for "Reference" not wrap, to navigational improvements like having table-of-contents for each page, it could feel a lot more polished.

**Comment by gauntface** [comment]
Moved Migration Guide to meta tracking bug and added Taylors suggestions to v3 tracking bug
